### PR TITLE
Extract features into their own components

### LINKED ISSUE #2: Separate layers into own namespaces

### PR DESCRIPTION
**Pull request by kliph**
- Further closes #2

### CODE REVIEW

**Comment by kliph** [comment]
@ryanhinkel what do you think about moving toward a directory structure that groups `skybox` and `state`?  

Something like:

```
➠ tree src/
src/
└── sunrise
    ├── component.cljs
    ├── core.cljs
    ├── mountain.cljs
    ├── skybox
    │   ├── core.cljs
    │   ├── sky.cljs
    │   └── sun.cljs
    ├── state
    │   ├── core.cljs
    │   ├── mountain.cljs
    │   └── window.cljs
    └── web.clj
```

I think it can be a future issue that we tackle separate from this PR.

**Review by ryanhinkel — APPROVED** [review]

**Comment by ryanhinkel** [comment]
RE:
```
src/
└── sunrise
    ├── component.cljs
    ├── core.cljs
    ├── mountain.cljs
    ├── skybox
    │   ├── core.cljs
    │   ├── sky.cljs
    │   └── sun.cljs
    ├── state
    │   ├── core.cljs
    │   ├── mountain.cljs
    │   └── window.cljs
    └── web.clj
```
I'm not sure I want to encourage a namespace hierarchy on all components. How would you feel about having all components in a components directory, i.e. `sunrise.components.mountain` and then nest those namespaces as necessary?

An example of where nesting doesn't make sense: we may decide that the sun needs to be painted in front of the skybox later.

Somewhere where it would make sense: maybe a mountain has whitecaps.

**Comment by kliph** [comment]
I see what you mean.  I like the idea of putting components in a `components` namespace.

**Comment by kliph** [comment]
@ryanhinkel I created #22 to capture this suggestion.

**Pull request merged**
